/** Responsive image widths generated by scripts/sync-images.mjs */
export const IMAGE_WIDTHS = [480, 768, 1200] as const;

export type ImageWidth = (typeof IMAGE_WIDTHS)[number];

/** Strip an existing -w{width} suffix so helpers are idempotent */
export function baseSrc(src: string): string {
  return src.replace(/-w\d+(\.[a-z]+)$/i, '$1');
}

/** Insert -w{width} before file extension */
export function variantSrc(src: string, width: ImageWidth): string {
  return baseSrc(src).replace(/(\.[a-z]+)$/i, `-w${width}$1`);
}

export function buildSrcSet(src: string, widths: readonly number[] = IMAGE_WIDTHS): string {
  const base = baseSrc(src);
  const parts = widths.map((w) => `${variantSrc(base, w as ImageWidth)} ${w}w`);
  parts.push(`${base} 1600w`);
  return parts.join(', ');
}

/** Smallest variant for mobile LCP preload */
export function preloadSrc(src: string, width: ImageWidth = 768): string {
  return variantSrc(src, width);
}

export function isResponsiveVariant(path: string): boolean {
  return /-w\d+\.(jpe?g|webp)$/i.test(path);
}
